# Generated by Django 4.0.3 on 2022-03-11 22:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.SmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('license', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('unverified', 'Не проверен'), ('verified', 'Проверен'), ('blocked', 'Заблокирован')], default='unverified', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField(default='')),
                ('impurity', models.SmallIntegerField(default='')),
                ('price', models.SmallIntegerField(default='')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sended', 'Отправлено'), ('onreview', 'На рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('todelete', 'На удаление')], default='draft', max_length=20)),
                ('delivery_method', models.CharField(choices=[('removal', 'Вывоз'), ('delivery', 'Доставка')], max_length=20)),
                ('removal_address', models.CharField(max_length=300)),
                ('delivery_range_from', models.CharField(max_length=500)),
                ('delivery_range_max', models.SmallIntegerField(default='', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)])),
                ('delivery_range_price', models.SmallIntegerField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.wastecategory')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.supplier')),
            ],
        ),
    ]
