# Generated by Django 4.0.3 on 2022-03-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='inn',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
