# Generated by Django 4.0.3 on 2022-04-12 23:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0004_alter_supplier_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.wastecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='delivery_method',
            field=models.CharField(choices=[('removal', 'Вывоз'), ('delivery', 'Доставка')], max_length=20, verbose_name='Способ поставки'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='delivery_range_from',
            field=models.CharField(max_length=500, null=True, verbose_name='Доставка из'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='delivery_range_max',
            field=models.PositiveSmallIntegerField(default='', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)], verbose_name='Макс. расстояние доставки'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='delivery_range_price',
            field=models.PositiveSmallIntegerField(default='', null=True, verbose_name='Стоимость доставки, руб/км'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='impurity',
            field=models.PositiveSmallIntegerField(default='', verbose_name='Засор'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.PositiveIntegerField(default='', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='removal_address',
            field=models.CharField(max_length=300, null=True, verbose_name='Адрес вывоза'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('sended', 'Отправлено'), ('onreview', 'На рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('todelete', 'На удаление')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='weight',
            field=models.PositiveIntegerField(default='', verbose_name='Вес, кг'),
        ),
    ]
