# Generated by Django 4.0.3 on 2022-04-12 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_offer_category_alter_offer_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='delivery_range_from',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Доставка из'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='delivery_range_max',
            field=models.PositiveSmallIntegerField(blank=True, default='', null=True, validators=[django.core.validators.MaxValueValidator(5000)], verbose_name='Макс. расстояние доставки'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='delivery_range_price',
            field=models.PositiveSmallIntegerField(blank=True, default='', null=True, verbose_name='Стоимость доставки, руб/км'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='removal_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес вывоза'),
        ),
    ]
