# Generated by Django 4.0.3 on 2022-04-13 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_offer_delivery_range_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='delivery_range_max',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5000)], verbose_name='Макс. расстояние доставки'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='delivery_range_price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Стоимость доставки, руб/км'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('sended', 'Отправлено'), ('onreview', 'На рассмотрении'), ('prerejected', 'Предварительно отклонено'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('todelete', 'На удаление')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
